### PR TITLE
Usermod multiple groups

### PR DESCRIPTION
**Pull request by martbhell**
Up for discussion how you would like to handle this :)

Fail early or skip the usermod task?

### CODE REVIEW

**Comment by martbhell** [comment]
https://travis-ci.com/github/CSCfi/ansible-role-users/jobs/513053778#L3258-L3259 looks like:

```
agroup:x:27001:admin2,admin5,user11,user10
bgroup:x:27002:admin4,admin5,admin8,user11
```

After this change == user11 is added to both agroup and bgroup when groups is a list

**Comment by junousi** [comment]
You both document a requirement for string and add a test for (non-string) list. My brain is running a bit slow so I don't understand why not add a test for the multi-group string?

Also is the pip-ubuntu failure related to this?

**Comment by martbhell** [comment]
I think it's already tested in https://github.com/CSCfi/ansible-role-users/blob/fc7d13287660ed1f07965ba331850966c62c99ac/tests/test_idempotency.yml#L13 scenario

Ubuntu failure looks unrelated. Some pip install dependency error

**Comment by junousi** [comment]
D'ohhhh, thanks! Also, as always, it helps if one actually reads the commits in-order.

*moral and mental approval granted until the green button appears*

**Comment by VilleS1** [comment]
Not needed anymore because the other PR was merged? Closing.

**Pull request closed without merging**
